name: Periodic health check

on:
  push:
    branches: 
      - main

jobs:
  health-check:
    steps:
    - name: Check url
      if: ${{ contains(join(github.event.commits.*.message, ', '), '#health')) }}
      uses: jtalk/url-health-check-action@v4
      with:
        url: https://full-stack-open-pokedex-summer-log-9248.fly.dev/
