name: Periodic health check

on:
  schedule:
    - cron: '5 * * * *'

jobs:
  health-check:
    runs-on: ubuntu-20.04
    if: ${{ contains(join(github.event.commits.*.message, ', '), '#health') }}
    steps:
    - name: Check health url
      uses: jtalk/url-health-check-action@v4
      with:
        url: https://full-stack-open-pokedex-summer-log-9248.fly.dev/health
