name: Hello World!

on:
  push:
    branches:
      - test

jobs:
  show-github-actions-data:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: display all github context
        env:
          CONTEXT: ${{ toJson(github) }}
        run: echo "$CONTEXT"

      - name: display event data
        env:
          EVENTS_DATA: ${{ toJson(github.event) }}
        run: echo "$EVENTS_DATA"

      - name: predicts whether this is a merge
        env:
          IS_MERGE: ${{ contains(join(github.commits.*.distinct, ', '), 'false') }}
        run: echo "is merge? $IS_MERGE"

      - name: commits distinctness array
        env:
          INFO: ${{ join(github.commits.*.distinct, ', ') }}
        run: echo "array: $INFO"
